"""evidence_file_hash_duplicate_check

Revision ID: 9804ccbdd10a
Revises: be7953370621
Create Date: 2026-08-20 05:13:55.847798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9804ccbdd10a'
down_revision: Union[str, None] = 'be7953370621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidences', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('evidences', sa.Column('duplicate_of_evidence_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_evidences_file_hash'), 'evidences', ['file_hash'], unique=False)
    op.create_foreign_key(
        'evidences_duplicate_of_evidence_id_fkey', 'evidences', 'evidences',
        ['duplicate_of_evidence_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('evidences_duplicate_of_evidence_id_fkey', 'evidences', type_='foreignkey')
    op.drop_index(op.f('ix_evidences_file_hash'), table_name='evidences')
    op.drop_column('evidences', 'duplicate_of_evidence_id')
    op.drop_column('evidences', 'file_hash')
    # ### end Alembic commands ###
