"""report_lifecycle_dispute_ledger_rules

Revision ID: be7953370621
Revises: ec9e869e868c
Create Date: 2026-08-19 17:44:10.659197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7953370621'
down_revision: Union[str, None] = 'ec9e869e868c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'credit_ledger',
        sa.Column('factor_weight', sa.Float(), nullable=False, server_default='1.0'),
    )
    op.add_column(
        'credit_ledger',
        sa.Column('status_factor', sa.Float(), nullable=False, server_default='1.0'),
    )
    op.add_column(
        'discredit_ledger',
        sa.Column('factor_weight', sa.Float(), nullable=False, server_default='1.0'),
    )
    op.add_column(
        'discredit_ledger',
        sa.Column(
            'verification_impact_multiplier', sa.Float(), nullable=False, server_default='1.0'
        ),
    )
    op.add_column(
        'discredit_ledger',
        sa.Column('is_voided', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('discredit_ledger', sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('discredit_ledger', sa.Column('voided_by', sa.UUID(), nullable=True))
    op.add_column('discredit_ledger', sa.Column('voided_reason', sa.Text(), nullable=True))
    op.create_foreign_key(
        'discredit_ledger_voided_by_fkey', 'discredit_ledger', 'users',
        ['voided_by'], ['id'], ondelete='SET NULL',
    )
    op.add_column('disputes', sa.Column('resolved_by', sa.UUID(), nullable=True))
    op.add_column('disputes', sa.Column('resolution_notes', sa.Text(), nullable=True))
    op.create_foreign_key(
        'disputes_resolved_by_fkey', 'disputes', 'users',
        ['resolved_by'], ['id'], ondelete='SET NULL',
    )
    op.add_column('evidences', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('reference_key', sa.String(length=255), nullable=True))
    op.add_column('reports', sa.Column('duplicate_of_report_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_reports_reference_key'), 'reports', ['reference_key'], unique=False)
    op.create_foreign_key(
        'reports_duplicate_of_report_id_fkey', 'reports', 'reports',
        ['duplicate_of_report_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###

    # --- Manual: Verification Status Rules rework (2.3) ---
    # Alembic autogenerate cannot diff Postgres ENUM member renames, so the
    # report_status type is rebuilt by hand. SQLAlchemy's Enum(PyEnum) binds
    # the member *name* (uppercase), matching every other enum in this
    # project (see report_visibility, user_role, dispute_status, ...), so
    # the new type must use uppercase labels too — remapping:
    #   PENDING -> UNVERIFIED, UNDER_REVIEW -> PENDING_REVIEW,
    #   VERIFIED -> VERIFIED, REJECTED -> REJECTED, DISPUTED -> APPEALED.
    op.execute("ALTER TYPE report_status RENAME TO report_status_old")
    op.execute(
        "CREATE TYPE report_status AS ENUM "
        "('UNVERIFIED', 'PENDING_REVIEW', 'VERIFIED', 'REJECTED', 'APPEALED', 'VOIDED')"
    )
    op.execute("ALTER TABLE reports ALTER COLUMN status DROP DEFAULT")
    op.execute(
        """
        ALTER TABLE reports ALTER COLUMN status TYPE report_status USING (
            CASE status::text
                WHEN 'PENDING' THEN 'UNVERIFIED'
                WHEN 'UNDER_REVIEW' THEN 'PENDING_REVIEW'
                WHEN 'VERIFIED' THEN 'VERIFIED'
                WHEN 'REJECTED' THEN 'REJECTED'
                WHEN 'DISPUTED' THEN 'APPEALED'
                ELSE 'UNVERIFIED'
            END
        )::report_status
        """
    )
    op.execute("ALTER TABLE reports ALTER COLUMN status SET DEFAULT 'UNVERIFIED'")
    op.execute("DROP TYPE report_status_old")

    # Drop the server_default helpers now that existing rows are backfilled —
    # new inserts must always pass an explicit value from the service layer.
    op.alter_column('credit_ledger', 'factor_weight', server_default=None)
    op.alter_column('credit_ledger', 'status_factor', server_default=None)
    op.alter_column('discredit_ledger', 'factor_weight', server_default=None)
    op.alter_column('discredit_ledger', 'verification_impact_multiplier', server_default=None)
    op.alter_column('discredit_ledger', 'is_voided', server_default=None)


def downgrade() -> None:
    # --- Manual: revert report_status enum rework ---
    op.execute("ALTER TYPE report_status RENAME TO report_status_new")
    op.execute(
        "CREATE TYPE report_status AS ENUM "
        "('PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'DISPUTED')"
    )
    op.execute("ALTER TABLE reports ALTER COLUMN status DROP DEFAULT")
    op.execute(
        """
        ALTER TABLE reports ALTER COLUMN status TYPE report_status USING (
            CASE status::text
                WHEN 'UNVERIFIED' THEN 'PENDING'
                WHEN 'PENDING_REVIEW' THEN 'UNDER_REVIEW'
                WHEN 'VERIFIED' THEN 'VERIFIED'
                WHEN 'REJECTED' THEN 'REJECTED'
                WHEN 'APPEALED' THEN 'DISPUTED'
                WHEN 'VOIDED' THEN 'REJECTED'
                ELSE 'PENDING'
            END
        )::report_status
        """
    )
    op.execute("ALTER TABLE reports ALTER COLUMN status SET DEFAULT 'PENDING'")
    op.execute("DROP TYPE report_status_new")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reports_duplicate_of_report_id_fkey', 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_reference_key'), table_name='reports')
    op.drop_column('reports', 'duplicate_of_report_id')
    op.drop_column('reports', 'reference_key')
    op.drop_column('evidences', 'comment')
    op.drop_constraint('disputes_resolved_by_fkey', 'disputes', type_='foreignkey')
    op.drop_column('disputes', 'resolution_notes')
    op.drop_column('disputes', 'resolved_by')
    op.drop_constraint('discredit_ledger_voided_by_fkey', 'discredit_ledger', type_='foreignkey')
    op.drop_column('discredit_ledger', 'voided_reason')
    op.drop_column('discredit_ledger', 'voided_by')
    op.drop_column('discredit_ledger', 'voided_at')
    op.drop_column('discredit_ledger', 'is_voided')
    op.drop_column('discredit_ledger', 'verification_impact_multiplier')
    op.drop_column('discredit_ledger', 'factor_weight')
    op.drop_column('credit_ledger', 'status_factor')
    op.drop_column('credit_ledger', 'factor_weight')
    # ### end Alembic commands ###
